plugins {
    id 'com.android.application'
}

android {
    namespace 'dz.depannage.app'
    compileSdk 35

    defaultConfig {
        applicationId "dz.depannage.app"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    packaging {
        resources {
            excludes += [
                "META-INF/DEPENDENCIES",
                "META-INF/LICENSE",
                "META-INF/LICENSE.txt",
                "META-INF/NOTICE",
                "META-INF/NOTICE.txt"
            ]
        }
    }
}

configurations.all {
    resolutionStrategy.eachDependency { details ->
        if (details.requested.group == "org.jetbrains.kotlin") {
            details.useVersion "1.8.22"
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.webkit:webkit:1.12.1'
    implementation 'org.osmdroid:osmdroid-android:6.1.20'
}
